version: '2'

services:
  load:
    build:
      context: ./module
      dockerfile: Dockerfile.template
      args:
        # Modify to the desired balenaOS version
        OS_VERSION: 2.112.12
        # Modify to the git token for the lincdadrv repository
        GITTOKEN: ghp_REPLACEBYYOURTOKEN
    privileged: true
    restart: on-failure
  check:
    privileged: true
    build:
      context: ./check
      dockerfile: Dockerfile.template
    depends_on:
      - load
